version: '3'
services:
  backend:
    container_name: btfd-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
  ui:
    container_name: btfd-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8000:80
    restart: always
    depends_on:
      - backend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongo:
    container_name: btfd-mongo
    image: mongo:latest
    ports:
      - 37017:27017
